[theme]

# Primary accent for interactive elements
primaryColor = '#835DFF'

# Background color for the main content area
backgroundColor = '#191919'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#161616'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
showSidebarBorder=1


[client]
showSidebarNavigation = false

[server]
fileWatcherType = "poll"